### ISSUE TITLE
爬取次数过多导致被拦截？原因未知

### ISSUE THREAD

**Issue by FireAngelx** [foyoux/pygtrans#17]
使用的是多线程，但是8个线程都被拦了，并且是在翻译两个小时之后被拦截的，正常翻译没有问题，整个程序需要三个小时跑完，偶尔有成功，失败的原因全都如下
Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /translate_a/t?tl=en&sl=auto&ie=UTF-8&oe=UTF-8&client=at&dj=1&format=text&v=1.0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\PythonProjects\pythonProject1\get_threading.py", line 143, in run
    body_str = t.translate(str(body_str))
  File "D:\PythonProjects\pythonProject1\get_translation.py", line 9, in translate
    return self.client.translate(text).translatedText
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\pygtrans\Translate.py", line 149, in translate
    response = self.__translate(q=q, target=target, source=source, fmt=fmt, v='1.0')
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\pygtrans\Translate.py", line 172, in __translate
    response = self.session.post(
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\PythonProjects\pythonProject1\venv\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /translate_a/t?tl=en&sl=auto&ie=UTF-8&oe=UTF-8&client=at&dj=1&format=text&v=1.0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
以上是某一个线程报的错，我个人的代理池只设置了两个{'https': 'http://localhost:15732', 'http': 'http://localhost:15732'}，domain='com'。
个人感觉是不是网站把UA给黑了，如果是的话要怎样改才能换UA呢，没有找到对应接口，或者说增大代理池就可以。
不太明白报错原因以及改正方法，求大佬指点一二，工程量比较大，总是跑一半程序然后卡掉也不是办法。
应该不是QPS过大导致的，因为最后一个线程也是这样断的。

**Comment by chengs2035** [comment]
qps是多少呀?

**Comment by lemisky** [comment]
> qps是多少呀? 

没有具体的值，一次翻译多点，减少请求次数，一次一万条句子，比较合适。
